package org.curtis.musicxml.direction.directiontype.percussion;

public enum MetalType {
    AGOGO,
    ALMGLOCKEN,
    BELL,
    BELL_PLATE,
    BELL_TREE,
    BRAKE_DRUM,
    CENCERRO,
    CHAIN_RATTLE,
    CHINESE_CYMBAL,
    COWBELL,
    CRASH_CYMBALS,
    CROTALE,
    CYMBAL_TONGS,
    DOMED_GONG,
    FINGER_CYMBALS,
    FLEXATONE,
    GONG,
    HI_HAT,
    HI_HAT_CYMBALS,
    HANDBELL,
    JAW_HARP,
    JINGLE_BELLS,
    MUSICAL_SAW,
    SHELL_BELLS,
    SISTRUM,
    SIZZLE_CYMBAL,
    SLEIGH_BELLS,
    SUSPENDED_CYMBAL,
    TAM_TAM,
    TAM_TAM_WITH_BEATER,
    TRIANGLE,
    VIETNAMESE_HAT
}
