package org.curtis.ui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class MusicXmlTasks {
    private JPanel taskForm;
    private JLabel tasksHeader;
    private JPanel headerPanel;

    public MusicXmlTasks() {

    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("MusicXmlTasks");
        frame.setContentPane(new MusicXmlTasks().taskForm);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        taskForm = new JPanel();
        taskForm.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        taskForm.setBackground(new Color(-1));
        headerPanel = new JPanel();
        headerPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 400, 0), -1, -1));
        headerPanel.setBackground(new Color(-1));
        taskForm.add(headerPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        tasksHeader = new JLabel();
        tasksHeader.setBackground(new Color(-1));
        tasksHeader.setFont(new Font(tasksHeader.getFont().getName(), Font.BOLD, 20));
        tasksHeader.setText("MusicXmlTasks");
        headerPanel.add(tasksHeader, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return taskForm;
    }
}
